version: "3.7"

services:
  java:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: nebula-java
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
      - ./maven:/.m2